// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Button': string;
  'Dropdown': string;
  'DropdownList': string;
}
export const cssExports: CssExports;
export default cssExports;
