// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Input': string;
  'dark': string;
  'default': string;
  'large': string;
  'light': string;
  'small': string;
}
export const cssExports: CssExports;
export default cssExports;
