// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Text': string;
  'default': string;
  'large': string;
  'small': string;
  'through-line': string;
  'underline': string;
}
export const cssExports: CssExports;
export default cssExports;
