// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'A': string;
  'default': string;
  'large': string;
  'small': string;
}
export const cssExports: CssExports;
export default cssExports;
