// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Flex': string;
  'aic': string;
  'aie': string;
  'ais': string;
  'fdc': string;
  'fdcr': string;
  'fdr': string;
  'fdrr': string;
  'jcb': string;
  'jcc': string;
  'jce': string;
  'jcs': string;
}
export const cssExports: CssExports;
export default cssExports;
