// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Checkbox': string;
  'active': string;
  'check': string;
  'default': string;
  'flag': string;
  'handle': string;
  'large': string;
  'small': string;
}
export const cssExports: CssExports;
export default cssExports;
